apiVersion: v1
kind: Service
metadata:
  name: next-k8s
  namespace: fe-experiment
spec:
  selector:
    app: next-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
