name: Build and Push App Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # 코드 읽기
      packages: write # GHCR에 push

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Node 설치 (Next.js 개발용)
      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) (선택) 의존성 캐시 – 빌드 속도Up
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4) Next.js 빌드 한 번 돌려서 타입·코드 오류 체크 (실패 시 워크플로 중단)
      - name: Install deps & run build
        run: |
          npm ci
          npm run build

      # 5) Docker Buildx 셋업
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6) GHCR 로그인
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7) Docker 이미지 빌드 & Push
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:image-${{ github.sha }}
